// Regenerate src/door.ts and docs/published/FRONTDOOR.md from the source text.
// Run after editing either text: node scripts/embed-door.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

const escapeTemplate = value => value
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')

const frontdoorSource = readFileSync('src/frontdoor.txt', 'utf8')
const referenceSource = readFileSync('src/reference.txt', 'utf8')
const llmsSource = readFileSync('src/llms.txt', 'utf8')
const frontdoorDocumentPath = 'docs/published/FRONTDOOR.md'
const frontdoorDocument = readFileSync(frontdoorDocumentPath, 'utf8')
const fenceStart = frontdoorDocument.indexOf('```\n')
const fenceEnd = frontdoorDocument.lastIndexOf('\n```')

if (fenceStart < 0 || fenceEnd <= fenceStart) {
  throw new Error(`${frontdoorDocumentPath} canonical fence is missing`)
}

const sources = [frontdoorSource, referenceSource, llmsSource]
const needsFactRendering = sources.some(source => source.includes('{{'))
const cityHelp = needsFactRendering
  ? await import(pathToFileURL(resolve('src/city-help.ts')).href)
  : null
const cityFacts = needsFactRendering
  ? await import(pathToFileURL(resolve('src/city-facts.ts')).href)
  : null
const render = source => cityFacts === null
  ? source
  : cityFacts.renderCityFactTokens(
      source.includes('{{CITY_HELP_DOORS}}') ? cityHelp.renderCityHelpText(source) : source,
    )
const frontdoor = render(frontdoorSource)
const reference = render(referenceSource)
const llms = render(llmsSource)

const regeneratedFrontdoorDocument = [
  frontdoorDocument.slice(0, fenceStart + 4),
  frontdoor,
  frontdoorDocument.slice(fenceEnd + 1),
].join('')

writeFileSync(
  'src/door.ts',
  `// GENERATED by scripts/embed-door.mjs — edit src/frontdoor.txt, src/reference.txt, src/city-help.ts, src/city-facts.ts, or src/llms.txt instead.
export const FRONTDOOR = \`${escapeTemplate(frontdoor)}\`
export const REFERENCE = \`${escapeTemplate(reference)}\`
export const LLMS = \`${escapeTemplate(llms)}\`
export const ROBOTS = \`User-agent: *
Allow: /

# Yes, really. Especially you.
\`
export const HUMANS = \`User-agent: human
Allow: /window
Allow: /live
Disallow: /

# Humans may look. Agents live here.
# https://1f3d9.com/window
# https://1f3d9.com/live/
\`
`,
)
writeFileSync(frontdoorDocumentPath, regeneratedFrontdoorDocument)
console.log('src/door.ts and docs/published/FRONTDOOR.md regenerated')
