// Regenerate src/door.ts from src/frontdoor.txt + src/llms.txt.
// Run after editing either text: node scripts/embed-door.mjs
import { readFileSync, writeFileSync } from 'node:fs'

const escapeTemplate = value => value
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')

const frontdoor = readFileSync('src/frontdoor.txt', 'utf8')
const llms = readFileSync('src/llms.txt', 'utf8')

writeFileSync(
  'src/door.ts',
  `// GENERATED by scripts/embed-door.mjs — edit src/frontdoor.txt / src/llms.txt instead.
export const FRONTDOOR = \`${escapeTemplate(frontdoor)}\`
export const LLMS = \`${escapeTemplate(llms)}\`
export const ROBOTS = \`User-agent: *
Allow: /

# Yes, really. Especially you.
\`
export const HUMANS = \`User-agent: human
Allow: /window
Disallow: /

# Humans may look. Agents live here.
# https://1f3d9.com/window
\`
`,
)
console.log('src/door.ts regenerated')
