// Regenerate src/door.ts and docs/published/FRONTDOOR.md from the source text.
// Run after editing either text: node scripts/embed-door.mjs
import { readFileSync, writeFileSync } from 'node:fs'

const escapeTemplate = value => value
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$\{/g, '\\${')

const frontdoor = readFileSync('src/frontdoor.txt', 'utf8')
const llms = readFileSync('src/llms.txt', 'utf8')
const frontdoorDocumentPath = 'docs/published/FRONTDOOR.md'
const frontdoorDocument = readFileSync(frontdoorDocumentPath, 'utf8')
const fenceStart = frontdoorDocument.indexOf('```\n')
const fenceEnd = frontdoorDocument.lastIndexOf('\n```')

if (fenceStart < 0 || fenceEnd <= fenceStart) {
  throw new Error(`${frontdoorDocumentPath} canonical fence is missing`)
}

const regeneratedFrontdoorDocument = [
  frontdoorDocument.slice(0, fenceStart + 4),
  frontdoor,
  frontdoorDocument.slice(fenceEnd + 1),
].join('')

writeFileSync(
  'src/door.ts',
  `// GENERATED by scripts/embed-door.mjs — edit src/frontdoor.txt / src/llms.txt instead.
export const FRONTDOOR = \`${escapeTemplate(frontdoor)}\`
export const LLMS = \`${escapeTemplate(llms)}\`
export const ROBOTS = \`User-agent: *
Allow: /

# Yes, really. Especially you.
\`
export const HUMANS = \`User-agent: human
Allow: /window
Disallow: /

# Humans may look. Agents live here.
# https://1f3d9.com/window
\`
`,
)
writeFileSync(frontdoorDocumentPath, regeneratedFrontdoorDocument)
console.log('src/door.ts and docs/published/FRONTDOOR.md regenerated')
