export const PUBLIC_EVENT_LABELS = Object.freeze({
  register: 'moved into the city',
  rotate: 'rotated their key',
  home_set: 'set their home',
  place_created: 'founded a place',
  place_edited: 'changed a place',
  kind_invented: 'invented a kind',
  kind_revised: 'revised a kind',
  trait_coined: 'coined a trait',
  thing_created: 'made a thing',
  thing_crafted: 'crafted a thing from ingredients',
  thing_edited: 'changed a thing',
  thing_moved: 'moved a thing',
  thing_upgraded: 'upgraded a thing',
  thing_withdrawn: 'withdrew a thing',
  laws_changed: 'changed local laws',
  action: 'acted in the city',
  effect_scheduled: 'set a stored effect in motion',
  effect_resolved: 'resolved a stored effect',
  note: 'left a note',
  agreement: 'wrote an agreement',
  agreement_accession: 'opened an agreement to later signers',
  agreement_sign: 'signed an agreement',
  transfer: 'gave away property',
  transfer_offer: 'offered property for sale',
  sale: 'bought property',
  transfer_cancel: 'canceled a sale offer',
  world_listed: 'listed a thing on the world market',
  world_sale: 'bought a thing through the world market',
  world_cancel: 'canceled a world market listing',
  payment_repair: 'recorded a host payment correction',
  flag: 'flagged a public record',
  moderation: 'used a logged maintainer power',
})

export const PUBLIC_EVENT_KINDS = Object.freeze(Object.keys(PUBLIC_EVENT_LABELS))

export const PUBLIC_EVENT_DETAIL_ID_FIELDS = Object.freeze([
  'resident_id',
  'place_id',
  'from_place_id',
  'to_place_id',
  'thing_id',
  'kind_id',
  'trait_id',
  'agreement_id',
  'note_id',
  'transfer_id',
  'offer_id',
  'flag_id',
  'target_id',
  'asset_id',
  'parent_id',
  'action_id',
  'effect_id',
  'pending_effect_id',
  'moderation_id',
] as const)

export const PUBLIC_EVENT_DETAIL_SCALAR_FIELDS = Object.freeze([
  'id',
  'type',
  'target_type',
  'asset_type',
  'action',
  'mode',
  'status',
  'channel',
] as const)
