export const CITY_CREDIT_HISTORY_DEFAULT = 20
export const CITY_CREDIT_HISTORY_MAX = 50
export const LATER_HOLDER_PAGE_DEFAULT = 10
export const LATER_HOLDER_PAGE_MAX = 200
export const PUBLIC_REPLAY_ROW_CEILING = 800
export const PUBLIC_REPLAY_NOTE_LINES_MAX_BYTES = 512_000
